### ISSUE TITLE
How do I export the read density for each bin in the function (MetageneAnalysisForTheWholeRegions)?

### ISSUE THREAD

**Issue by cornecu** [xryanglab/RiboMiner#2]
Hi, thank you so much for the ribominer package to help in my ribosome profiling analysis. 

I am wondering how to export the the read density for each bin in the options of the function (MetageneAnalysisForTheWholeRegions)? Is there any options for this command? Do I need to modify this source code to do that?

Thank you so much in advance.

**Comment by sherkinglee** [comment]
Hi, 
Indeed, I did not output the read density for each bin in the original function (MetageneAnalysisForTheWholeRegions) while its plot script (PlotMetageneAnalysisForTheWholeRegions) does output a density vector which used for plots (output_prefix_scaled_density_dataframe.txt). Considering that many users need this output file, I renewed RiboMiner and uploaded it (0.2.3.2) that could output read density for each bin for each transcript that meets our criteria.  In this case, MetageneAnalysisForTheWholeRegions could output 3 kinds of files (a pdf file, a density file that used for the final plot, and several files containing read density for each bin (one sample, one read density file)).  Since we may have more modifications for RiboMiner, we did not upload it to PyPi. You could access it here (https://github.com/xryanglab/RiboMiner/releases/tag/v0.2). 

Thanks for your feedback! I hope it could be helpful to you.

Sherking

**Comment by cornecu** [comment]
> Hi,
> Indeed, I did not output the read density for each bin in the original function (MetageneAnalysisForTheWholeRegions) while its plot script (PlotMetageneAnalysisForTheWholeRegions) does output a density vector which used for plots (output_prefix_scaled_density_dataframe.txt). Considering that many users need this output file, I renewed RiboMiner and uploaded it (0.2.3.2) that could output read density for each bin for each transcript that meets our criteria. In this case, MetageneAnalysisForTheWholeRegions could output 3 kinds of files (a pdf file, a density file that used for the final plot, and several files containing read density for each bin (one sample, one read density file)). Since we may have more modifications for RiboMiner, we did not upload it to PyPi. You could access it here (https://github.com/xryanglab/RiboMiner/releases/tag/v0.2).
> 
> Thanks for your feedback! I hope it could be helpful to you.
> 
> Sherking

Hi Sherking,

Thank you so much for quick response. The output read density is RPKM and if I have three replicates for one sample, it will output the total sum of RPKM, yes? If I want to get mean ribodensity, I can divide them by three, yes? or I can use ribominer plot function or enrichmentMeanDensity to get mean RPKM density? 

Thank you so much again for your help.

**Comment by sherkinglee** [comment]
Hi,
I am a little confused about your question.  Actually, the "read density" for each bin generated by "MetageneAnalysisForTheWholeRegions" script is a scaled vector of the raw read counts normalized by both the transcript length and the mean read density of each transcript rather than a RPKM vector.  The _RiboDensityAtEachPosition_  could output raw read count at each codon position for each transcript and _CoverageOfEachTrans_  with "--mode count" could output RPM density for each transcript at codons. If you have three replicates for each sample, those functions would generate three density files. If you want to get the mean ribosome density, you can use _enrichmentMeanDensity_  to the get mean RPM density at each codon position. Or you can use your own custom scripts to calculate the mean value.  Unfortunately, I did not have a script to calculate the total sum of RPKM values for each transcript or each bin when the RiboMiner was published. But you can use _ModifyHTseq_ to calculate raw read counts for each gene if you need. 

I hope this could be helpful to you.

Sherking

**Comment by cornecu** [comment]
> Hi,
> I am a little confused about your question. Actually, the "read density" for each bin generated by "MetageneAnalysisForTheWholeRegions" script is a scaled vector of the raw read counts normalized by both the transcript length and the mean read density of each transcript rather than a RPKM vector. The _RiboDensityAtEachPosition_ could output raw read count at each codon position for each transcript and _CoverageOfEachTrans_ with "--mode count" could output RPM density for each transcript at codons. If you have three replicates for each sample, those functions would generate three density files. If you want to get the mean ribosome density, you can use _enrichmentMeanDensity_ to the get mean RPM density at each codon position. Or you can use your own custom scripts to calculate the mean value. Unfortunately, I did not have a script to calculate the total sum of RPKM values for each transcript or each bin when the RiboMiner was published. But you can use _ModifyHTseq_ to calculate raw read counts for each gene if you need.
> 
> I hope this could be helpful to you.
> 
> Sherking

Hi Sherking,

Thank you so much for your explanation. It's super helpful for me.
