### ISSUE TITLE
RiboMiner Polarity Calculation

### ISSUE THREAD

**Issue by StevenWingett** [xryanglab/RiboMiner#4]
Hi again,

I was in contact with you recently regarding the RiboMiner Polarity Calculation.  I had a further question about this function, for I noticed in Figure 4B of your RiboMiner paper (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03670-8) the Polarity Plot displays a P-value when comparing two distributions.  I hope you would be able to answer a few questions I have about generating this P-value:

1)	When I run the PolarityCalculation I do not generate a P-value on the plot.  How should I instruct RiboMiner to return this value?  (Please accept my apologies if I missed this in the documentation).

2)	Also, I would like to know what statistical test was used to perform this calculation?   

3)	Finally, is it possible to instruct RiboMiner to perform test this to compare 2 different groups of samples (each group contains 3 replicates).

I hope my queries make sense and I've not missed something obvious.  Many thanks once again for your assistance.

Regards,
Steven

**Comment by sherkinglee** [comment]
Hi Steven,
I am sorry for making it so confusing! Actually, I did not output any statistical results for the polarity scores because we intended to make it much more flexible for the users which means you can choose a proper statistical test for the results you get. The P-value in Figure 4B was added manually under the suggestions of reviewers.  At that time, I just used a simple t.test or wilcox.test to get the p values. And you can also use KS test to do this because we indeed do not know the real distribution of those polarity scores. As for the last question, we did not perform differential test for those polarity scores between 2 groups like the way DEseq2 acts though we actually intended to before.  But recently I found another tool papolarity (https://github.com/autosome-ru/papolarity ) that may help you do this.

By the way, since last update, another issue occured. Thus, you can re-install the lastest version of RiboMiner to avoid failure usage. Hope you can find RiboMiner useful for your team.

Best wishes,
Sherking

**Comment by StevenWingett** [comment]
Hi Sherking,

Thanks for getting back to me about the polarity calculation.  That makes sense.

All the best,
Steven
