### ISSUE TITLE
RiboDensityAtEachPosition: coverage and density most of are 0

### ISSUE THREAD

**Issue by junjunlab** [xryanglab/RiboMiner#7]
Hello, I check my samples coverage and density files after **RiboDensityAtEachPosition**  step, I found that most protein-coding genes are 0, is it normal? Besides the **periodicity**  of my reads is bad, so the frame0 densitys are very low? I have tried use reads length **ALL** in the **attributes.txt**, but the results are same with before. Thank you for your reply!

best wishes,
zhangjun

**Comment by sherkinglee** [comment]
Hi Zhangjun,
Normally, we do not recommend using the ribosome profiling data if the periodicity of the sample is poor because we do not know whether the ribosome profiling has truly captured the RNA fragments protected by ribosomes. The coverage file contains coverage of each transcript and if most transcripts are 0, it suggests that your sample may be with low sequence depth.  Thus, most positions in your density files are also 0. Besides, sparsity is a typical feature of ribosome profiling data. Therefore, I recommed you to re-do the ribosome profiling assay to make sure you get the data with a good 3-nt periodicity and try to sequence more reads to make sure enough coverage. Usually, 3-4 million valid reads aligned to transcriptome are acceptable.

best,
Sherking

**Comment by junjunlab** [comment]
Hi Sherking,
Thank you for your advice! I will recheck my ribo-seq data and experiment process, thank you very much!
best,
Zhangjun
